name: snapshot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/package
        env:
          FUNDING_WALLET_CONFIG: ${{ secrets.FUNDING_WALLET_CONFIG }}
          CLOJARS_USERNAME: serge-medvedev
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
        with:
          mode: snapshot

